local M = {}

M.CAMERA_WIDTH = 800
M.CAMERA_HEIGHT = 480

M.GAME_WIDTH = 1280
M.GAME_HEIGHT = 720
M.GAME_ASPECT_W = M.GAME_WIDTH/M.GAME_HEIGHT
M.GAME_ASPECT_H = M.GAME_HEIGHT/M.GAME_WIDTH
M.GAME_SCALE = 0.6 --1  0 same width width - 1 same height . Min
M.GAME_MOVE_X = 0.3 -- 0 free zone in right. 1 free zone in left

M.GUI_WIDTH = 1280
M.GUI_HEIGHT = 720

M.POWER_LAZER_Z = 0.5
M.PLAYER_Z = 0.2
M.ENEMY_Z = 0.1
M.BULLET_Z = 0.3

M.PLAYER_GROUP = bit.tobit(1)
M.ENEMY_GROUP = bit.tobit(2)
M.COLLECTABLE_GROUP = bit.tobit(4)
M.PLAYER_BULLET_GROUP = bit.tobit(8)
M.PLAYER_LAZER_GROUP = bit.tobit(16)
M.ENEMY_BULLET_GROUP = bit.tobit(32)

M.PLAYER_MASK = bit.bor(M.ENEMY_GROUP, M.COLLECTABLE_GROUP, M.ENEMY_BULLET_GROUP)
M.ONLY_COLLECTABLE_MASK = bit.bor(M.COLLECTABLE_GROUP)
M.PLAYER_BULLET_MASK = bit.bor(M.ENEMY_GROUP)
M.ENEMY_MASK = bit.bor(M.PLAYER_GROUP, M.PLAYER_BULLET_GROUP, M.PLAYER_LAZER_GROUP)
M.ENEMY_BULLET_MASK = bit.bor(M.PLAYER_GROUP,M.PLAYER_LAZER_GROUP)
M.COLLECTABLE_MASK = bit.bor(M.PLAYER_GROUP)
M.ENEMY_ALL_MASK =  bit.bor(M.ENEMY_GROUP, M.ENEMY_BULLET_GROUP)


M.COLLECTABLE_BLUE = "blue"
M.COLLECTABLE_RED = "red"
M.COLLECTABLE_PURPLE = "purple"

M.OS = sys.get_sys_info().system_name

return M
